#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Error: you must provide an URL to index"
  echo "Usage: $0 <URL>"
  exit 1
fi

URL="$1"

if [ -z "${INDEXNOW_KEY}" ]; then
  echo "Error: INDEXNOW_KEY is not set"
  exit 1
fi

REQUEST_URL="https://api.indexnow.org/indexnow?url=${URL}&key=${INDEXNOW_KEY}"

curl -X GET "${REQUEST_URL}" -H "Transfer-Encoding: chunked" -d '{}'
